# Generated by Django 3.0 on 2019-12-24 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ctype', models.CharField(choices=[('Gaussian', 'Gaussian'), ('Primitive', 'Primitive'), ('CORPSE', 'CORPSE'), ('CinBB', 'CinBB'), ('CinSK', 'CinSK')], default='CinBB', max_length=10)),
                ('maximum_rabi_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=9, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('polar_angle', models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
