# Generated by Django 3.0 on 2019-12-21 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_types', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='controls',
            name='artist',
        ),
        migrations.AlterField(
            model_name='controls',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='controls',
            name='ctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controls.Control_Types'),
        ),
    ]
