# Generated by Django 3.0 on 2019-12-23 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_auto_20191221_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='controls',
            name='maximum_rabi_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=9, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='controls',
            name='polar_angle',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=9, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='controls',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
