# Generated by Django 3.0 on 2019-12-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_auto_20191223_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controls',
            name='ctype',
            field=models.CharField(choices=[('GAUS', 'Gaussian'), ('PRIM', 'Primitive'), ('CORP', 'CORPSE'), ('CINB', 'CinBB'), ('CINS', 'CinSK')], default='CINB', max_length=4),
        ),
        migrations.DeleteModel(
            name='Control_Types',
        ),
    ]
